### ISSUE TITLE
CLI script does not support ios correctly

### ISSUE THREAD

**Issue by sherbie** [Applifier/testdroid-ssa-client#19]
The testdroid_cmdline.sh script fails if the file provided for the -a option is a directory (in this case a .app or .ipa). It is supposed to allow these as an exception. When either of these two are provided, the script fails here: https://github.com/Applifier/testdroid-ssa-client/blob/master/testdroid_cmdline.sh#L470

**Comment by ujappelbe** [comment]
I think a .ipa is always a file so that should not fail here. We upload .ipa files in CI already. Best solution for now could be to accept also .zip files and upload those (for .app). 

But I am not sure how testdroid backend will react on anything other than .ipa or .apk file. Uploading several files (a folder) will not succeed. I think also uploading a zipped .app file might cause issues if they do any checks / try and install the package.

**Comment by sherbie** [comment]
It looks like the real problem is with .app uploads only since they are just directories. The Testdroid rest api does not support this type, so we can just check for the upload type to be .ipa or .apk.

**Comment by sherbie** [comment]
https://github.com/Applifier/testdroid-ssa-client/pull/20
